const car = [
  {
    state: 'new',
    status: 'available',
    price: 2000000,
    manufacturer: 'Toyota',
    model: 'pathfinder',
    body_type: 'car',
    image_url: 'fghjhjk',
    newPrice: 60000044,
  },
  {
    state: 'new',
    status: 'available',
    price: 2500000,
    manufacturer: 'Toyota',
    model: 'hilux',
    body_type: 'truck',
    image_url: 'fghjhjk',
  },
  {
    state: 'new',
    status: 'available',
    price: 2500000,
    manufacturer: 'Toyota',
    model: 'hilux',
    image_url: 'fghjhjk',
    body_type: 'truck',
  },
  {
    state: 'new',
    status: 'available',
    price: 5000000,
    manufacturer: 'Toyota',
    model: 'hilux',
    image_url: 'fghjhjk',
    body_type: 'truck',
  },
  {
    state: 'new',
    status: 'sold',
    price: 5000000,
    manufacturer: 'Toyota',
    model: 'hilux',
    image_url: 'fghjhjk',
    body_type: 'truck',
    newPrice: 80000000,
  },
  {
    state: 'used',
    status: 'sold',
    price: 4000000,
    manufacturer: 'Toyota',
    model: '530',
    body_type: 'SUV',
    image_url: 'fghjhjk',
    newPrice: 9000000,
  },
  {
    image_url: 'fghjhjk',
    newPrice: '',
  },
];

export default car;
